### ISSUE TITLE
telescope extension: does not work due to incorrectly named export + use of nil value

### ISSUE THREAD

**Issue by chrsm** [m-demare/attempt.nvim#1]
`lua/telescope/_extensions/attempt.lua` has the following issues:

- [line#8](https://github.com/m-demare/attempt.nvim/blob/main/lua/telescope/_extensions/attempt.lua#L8) attempts to concatenate a nil value - checks that `ext ~= ''`, but can get around this by checking for truthyness (`ext`, period).
- [line#49](https://github.com/m-demare/attempt.nvim/blob/main/lua/telescope/_extensions/attempt.lua#L49) incorrectly names the export to `attempts`, so the telescope extension doesn't work.

Submitting PR shortly if you are interested.

**Comment by chrsm** [comment]
p.s. thank you for this extension, it's great! i have so many scattered files all over the place and it's nice to have something to manage it for me.

**Comment by m-demare** [comment]
Glad you like it!
Thanks for the contribution, left a comment on the PR
