### ISSUE TITLE
Deleting attempts

### ISSUE THREAD

**Issue by LamprosPitsillos** [m-demare/attempt.nvim#7]
Can we expose the M.delete somehow in telescope ? Lets say <C-d> deletes the attempt.
If not, having a `ClearAttemps` command would be useful.
Maybe with arguments like `ext` ,ex `py` clears all python attempts.
Or `num` for the `num` oldest attempts, if attempts size < num delete all.
I tried making it my self but i dont understand your M.delete, and because it deletes files am too scared to play around with it XD. 
Thanks!

**Comment by m-demare** [comment]
Hi! Sorry for the delay, busy week
You can see the all the options in `:h attempt.delete_filtered()`, but for the usecases you proposed you can use it like this:
```lua
vim.ui.input({prompt= 'Choose extension: '}, function(res)
  attempt.delete_filtered {
    ext=res,
    -- max_to_delete = 5
  }
end)
```
You can easily turn it into a user command using `:h nvim_create_user_command()`, but i preferred to provide just a lua API to give more flexibility.
Also, I might end up adding the telescope picker too, but I had a couple of problems trying to get it working, and I think you can easily replicate all the functionality with this
