### ISSUE TITLE
Attempt buffer not recognized as one

### ISSUE THREAD

**Issue by Skyppex** [m-demare/attempt.nvim#9]
I've set up attempt to access .cs files. After creating an attempt buffer and trying to run it, it notifies me "Not an attempt buffer". Same happens when i try to delete the attempt buffer. Its the same if the file has any content or if its empty, its the same if i've :w the buffer or not.

My config for attempt (using Lazy):
```lua
return {
	"m-demare/attempt.nvim",
	dependencies = { "nvim-lua/plenary.nvim" },
	config = function()
		local attempt = require("attempt")
		attempt.setup({
			ext_options = { "lua", "py", "cs", "" },
			run = {
				cs = { "w", "dotnet script %" },
				py = { "w !python" }, -- Either table of strings or lua functions
				js = { "w !node" },
				lua = { "w", "luafile %" },
			},
		})
		require("telescope").load_extension("attempt")

		vim.keymap.set("n", "<leader>AN", attempt.new_select, { noremap = true, silent = true }) -- new attempt, selecting extension
		vim.keymap.set("n", "<leader>AI", attempt.new_input_ext, { noremap = true, silent = true }) -- new attempt, inputing extension
		vim.keymap.set("n", "<leader>AR", attempt.run, { noremap = true, silent = true }) -- run attempt
		vim.keymap.set("n", "<leader>AD", attempt.delete_buf, { noremap = true, silent = true }) -- delete attempt from current buffer
		vim.keymap.set("n", "<leader>AC", attempt.rename_buf, { noremap = true, silent = true }) -- rename attempt from current buffer
		vim.keymap.set("n", "<leader>AL", "<cmd>Telescope attempt<CR>", { noremap = true, silent = true }) -- search through attempts
	end,
}
```

**Comment by m-demare** [comment]
Hi! Thanks for the report, it should be working now
Btw, in your configuration to run cs files, there's a ! missing, it should be `cs = { "w", "!dotnet script %" },` (because it's an external command)

**Comment by Skyppex** [comment]
> Hi! Thanks for the report, it should be working now Btw, in your configuration to run cs files, there's a ! missing, it should be `cs = { "w", "!dotnet script %" },` (because it's an external command)

Hi, thanks for fixing it 😃 and for fixing my config for me 😂
It seems to work perfectly now👍
Phenomenal plugin btw, great work on it!
Is there any documentation for the syntax there specifically related to attempt or is this just lua or vim stuff?

**Comment by m-demare** [comment]
Thanks for the kind words <3

>  Is there any documentation for the syntax there specifically related to attempt or is this just lua or vim stuff?

You mean documentation for the plugin's implementation? There isn't anything specific, but it's mostly standard lua. The only "special" things is that it uses [plenary's](https://github.com/nvim-lua/plenary.nvim) libuv wrapper for async I/O, (see [filedata.lua](https://github.com/m-demare/attempt.nvim/blob/3905db768478a2152fd927ab5a8def85bc2e34e7/lua/attempt/filedata.lua)), and the implementation for the [telescope picker](https://github.com/m-demare/attempt.nvim/blob/3905db768478a2152fd927ab5a8def85bc2e34e7/lua/telescope/_extensions/attempt.lua) (which is [documented in the telescope repo](https://github.com/nvim-telescope/telescope.nvim/blob/7bd2f9b72f8449780b79bcf351534e2cd36ec43a/developers.md))
Other than that, the official Lua docs, and nvim's `:help` command for the nvim API are probably the best sources
